#print "hello world"
#print "hello Again"
#print "i like typing this"
#print "This is fun"
#print "Yay! printing."
#print "i'd much rather you 'not'. "
print "i seen i need to be silent in a world thst only shouts. "
